### ISSUE TITLE
Obtain the data

### ISSUE THREAD

**Issue by aimalz** [marin-hyatt/redshift_data_project#1]
As a first step, you'll need to get some data to work with!  To download a small dataset for the purpose of writing code that works before trying to learn anything about the data:

1. Go to the [SDSS SkyServer Search Form](http://skyserver.sdss.org/dr14/en/tools/search/form/searchform.aspx).
2. Select “galaxies” from the “Show me” menu.
3. Select “only objects with spectra” from the “for” menu.
4. Select the “1000” bubble from the “Num. of objects” choices.
5. Select all checkboxes for the “Image Data” choices.
6. Select all checkboxes for the “Spectral Data” choices.
7. Select the “CSV” bubble from the “Output format” choices.
8. Click “Submit query to SkyServer” and save the file.

Normally putting data on GitHub is a big no-no, but the file with 1000 galaxies will be small and very useful for getting help if your code breaks, so I'd encourage you, just this once, to add, commit, and push that file to the repository and use it when developing code.  

This issue can be closed when you have some data and are confident you can modify this procedure in the future when you need more or different data from the same source.

**Comment by marin-hyatt** [comment]
I closed this issue because I am confident I can do this again (I did this already with 1000 galaxies which won't be enough).
