### ISSUE TITLE
Context for multi-dimensional linear regression

### ISSUE THREAD

**Issue by aimalz** [marin-hyatt/redshift_data_project#3]
You've made a ton of progress on this, but let's step back and go over what exactly you're doing, since pretty much all machine learning is built on the same linear algebra underpinning regression.  It's best to build up from a strong foundation!

You can write [markdown](https://guides.github.com/features/mastering-markdown/) notes in Jupyter notebooks.  In your [linear regression notebook](https://github.com/marin-hyatt/redshift_data_project/blob/master/Untitled.ipynb) (which probably should have a descriptive name), try adding markdown cells explaining what you're doing in each cell.  In particular, see if you can relate your code to the math in [this paper](https://arxiv.org/pdf/1008.4686).

**Comment by marin-hyatt** [comment]
I commented on each (significant) cell with context. On the graphs, I explained what was being graphed and what were the results.
